### ISSUE TITLE
Help in using Angular 

### ISSUE THREAD

**Issue by wagons24** [dvdcastro/keystonejs-ng-skeleton#2]
Hi there, 

I have downloaded and installed the code. The issue I am facing is to run the angular code that I have. can you please help me how to configure index.html to run angular code

**Comment by dvdcastro** [comment]
@wagons24 Sorry for the late response. There is no index.html file in this project because this project uses the [jade](http://jade-lang.com/) template engine.

You have 2 places to look for angular code, in the jade templates and in the js files. The jade templates for the bootstrap-angular app are in [templates/views/angbootm](https://github.com/dvdcastro/keystonejs-ng-skeleton/tree/master/templates/views/ang_bootm) and the corresponding javascript files that have all the angular app are in [public/js/ang_bootm](https://github.com/dvdcastro/keystonejs-ng-skeleton/tree/master/public/js/ang_bootm). Modify these files and the keystone app to get your desired result.
